name: Build Images

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build_dist:
    name: Build dist
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ls
        shell: bash
        run: ls -l . && mkdir -p dist && echo 'hello' > dist/baz.txt && ls dist

      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: my-artifact
          path: dist/
          if-no-files-found: error
          retention-days: 1

      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

      # - uses: denoland/setup-deno@v2
      #   with:
      #     deno-version: v2.x

      # - name: Install dependencies
      #   run: deno install --allow-scripts=npm:sharp,npm:@parcel/watcher
      #
      # - name: Build dist
      #   run: deno task build

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ghcr.io/${{ github.repository }}
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}

  build_see:
    name: See build
    needs: [build_dist]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write

    steps:
      - name: Ls
        shell: bash
        run: ls -l .
